"""Generate ATLAS.md and docs/atlas.html from the detector registry.

The Atlas is data (src/syntropyrl/atlas.py) and the detectors are code
(src/syntropyrl/detectors/). This script joins them, so the published docs can
never describe a detector that does not ship, and a shipped detector can never
be missing from the docs. CI runs `--check` to enforce that.

    python scripts/build_atlas.py            # write the files
    python scripts/build_atlas.py --check    # fail if regeneration changes them
"""

from __future__ import annotations

import argparse
import html
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from syntropyrl.atlas import ENTRIES, FAMILY_BLURB, FAMILY_ORDER  # noqa: E402
from syntropyrl.detectors import catalog  # noqa: E402

BANNER = "<!-- generated by scripts/build_atlas.py - edit src/syntropyrl/atlas.py instead -->"


def _joined():
    """Join Atlas entries with the detector that implements them."""
    det = {d["code"]: d for d in catalog()}
    missing = sorted(set(det) - set(ENTRIES))
    if missing:
        raise SystemExit(
            "these detectors have no Atlas entry: {}\n"
            "Add them to src/syntropyrl/atlas.py.".format(", ".join(missing))
        )
    orphan = sorted(set(ENTRIES) - set(det))
    rows = []
    for fam in FAMILY_ORDER:
        for code, e in ENTRIES.items():
            if e["family"] != fam:
                continue
            rows.append({"code": code, "detector": det.get(code), **e})
    return rows, orphan


# --------------------------------------------------------------------------
# ATLAS.md
# --------------------------------------------------------------------------
def build_markdown(rows, orphan) -> str:
    out = [
        BANNER,
        "",
        "# The RL Failure Atlas",
        "",
        "Every way a reinforcement learning run can quietly fail, what it looks like,",
        "and what to do about it. Each entry that has a detector is checked automatically",
        "by `syntropyrl`; entries without one are still worth reading.",
        "",
        "Browsable version: <https://syntropyrl.dev/atlas.html>",
        "",
        "## Index",
        "",
        "| Code | Failure mode | Family | Detector |",
        "|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            "| [{code}](#{anchor}) | {title} | {family} | {det} |".format(
                code=r["code"],
                anchor=r["code"].lower(),
                title=r["title"],
                family=r["family"],
                det="yes" if r["detector"] else "not yet",
            )
        )
    if orphan:
        out += ["", "Entries without a detector yet: " + ", ".join(orphan) + "."]

    current = None
    for r in rows:
        if r["family"] != current:
            current = r["family"]
            out += ["", "---", "", "## {}".format(current.title()), "", "*{}*".format(FAMILY_BLURB.get(current, ""))]
        out += ["", "### {} - {}".format(r["code"], r["title"]), ""]
        if r.get("aka"):
            out.append("*Also called: {}*".format(", ".join(r["aka"])))
            out.append("")
        out += [
            "**Symptom.** {}".format(r["symptom"]),
            "",
            "**What syntropyrl measures.** {}".format(r["measure"]),
            "",
            "**Likely causes**",
            "",
        ]
        out += ["- {}".format(c) for c in r["causes"]]
        out += ["", "**Fixes, in order**", ""]
        out += ["{}. {}".format(i + 1, f) for i, f in enumerate(r["fixes"])]
        out += [
            "",
            "**Why it matters.** {}".format(r["cost"]),
            "",
            "```bash",
            r["repro"],
            "```",
        ]
    out += [
        "",
        "---",
        "",
        "## Contributing an entry",
        "",
        "If you have debugged an RL run at 2am, you know something that is not written",
        "down anywhere. A complete contribution is an Atlas entry, a repro scenario, a",
        "detector, and a test. See [CONTRIBUTING.md](CONTRIBUTING.md).",
        "",
    ]
    return "\n".join(out)


# --------------------------------------------------------------------------
# docs/atlas.html
# --------------------------------------------------------------------------
def _li(items):
    return "\n".join("          <li>{}</li>".format(html.escape(i)) for i in items)


def build_html(rows, orphan) -> str:
    cards = []
    current = None
    for r in rows:
        if r["family"] != current:
            current = r["family"]
            cards.append(
                '      <div class="family-head" data-family="{f}">\n'
                "        <h2>{title}</h2>\n"
                "        <p>{blurb}</p>\n"
                "      </div>".format(
                    f=current,
                    title=html.escape(current.title()),
                    blurb=html.escape(FAMILY_BLURB.get(current, "")),
                )
            )
        haystack = " ".join(
            [r["code"], r["title"], r["symptom"], " ".join(r.get("aka", []))]
        ).lower()
        cards.append(
            """      <article class="entry" id="{code}" data-family="{family}" data-search="{search}">
        <header class="entry-head">
          <div class="entry-title">
            <code class="code-chip">{code}</code>
            <h3>{title}</h3>
          </div>
          <div class="entry-meta">
            <span class="tag tag-{family}">{family}</span>
            <span class="tag {detcls}">{detlabel}</span>
            <a class="anchor-link" href="#{code}" aria-label="Link to {code}">#</a>
          </div>
        </header>
        {aka}
        <div class="entry-body">
          <div class="field">
            <span class="field-label">Symptom</span>
            <p>{symptom}</p>
          </div>
          <div class="field">
            <span class="field-label">What syntropyrl measures</span>
            <p>{measure}</p>
          </div>
          <div class="two-col">
            <div class="field">
              <span class="field-label">Likely causes</span>
              <ul>
{causes}
              </ul>
            </div>
            <div class="field">
              <span class="field-label">Fixes, in order</span>
              <ol>
{fixes}
              </ol>
            </div>
          </div>
          <div class="field cost">
            <span class="field-label">Why it matters</span>
            <p>{cost}</p>
          </div>
          <div class="repro">
            <span class="repro-label">Reproduce locally</span>
            <code>$ {repro}</code>
          </div>
        </div>
      </article>""".format(
                code=r["code"],
                family=r["family"],
                search=html.escape(haystack, quote=True),
                title=html.escape(r["title"]),
                detcls="tag-ok" if r["detector"] else "tag-todo",
                detlabel="detector shipped" if r["detector"] else "detector wanted",
                aka=(
                    '        <p class="aka">also called: {}</p>'.format(
                        html.escape(", ".join(r["aka"]))
                    )
                    if r.get("aka")
                    else ""
                ),
                symptom=html.escape(r["symptom"]),
                measure=html.escape(r["measure"]),
                causes=_li(r["causes"]),
                fixes=_li(r["fixes"]),
                cost=html.escape(r["cost"]),
                repro=html.escape(r["repro"]),
            )
        )

    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>RL Failure Atlas - syntropyrl</title>
<meta name="description" content="Every way a reinforcement learning run can quietly fail: symptom, cause, and fix for {n} documented failure modes." />
<link rel="stylesheet" href="./assets/styles.css" />
{banner}
</head>
<body>
<a class="skip-link" href="#atlas-main">Skip to content</a>
<header class="site-header">
  <div class="wrap header-inner">
    <a class="brand" href="./index.html"><span class="brand-mark" aria-hidden="true">&#129466;</span> syntropyrl</a>
    <nav class="site-nav">
      <a href="./index.html">Overview</a>
      <a href="./playground.html">Playground</a>
      <a class="current" href="./atlas.html">Atlas</a>
      <a class="btn-ghost" href="https://github.com/syntropyrl/syntropyrl">GitHub</a>
    </nav>
  </div>
</header>

<main id="atlas-main">
  <section class="atlas-hero">
    <div class="wrap narrow">
      <p class="eyebrow">Reference</p>
      <h1>The RL Failure Atlas</h1>
      <p class="lede">{n} documented ways a reinforcement learning run fails without crashing.
        Each entry gives the symptom you actually see, what to measure, the ranked causes, and
        the fix to try first.</p>
      <div class="atlas-controls">
        <label class="search-field">
          <span class="sr-only">Search the Atlas</span>
          <input id="atlas-search" type="search" placeholder="Search symptoms, e.g. &quot;reward flat&quot; or &quot;NaN&quot;" autocomplete="off" />
        </label>
        <div class="filter-row" role="group" aria-label="Filter by family">
          <button class="chip is-active" data-filter="all" type="button">All</button>
          <button class="chip" data-filter="numerics" type="button">Numerics</button>
          <button class="chip" data-filter="optimization" type="button">Optimization</button>
          <button class="chip" data-filter="reward" type="button">Reward</button>
          <button class="chip" data-filter="distribution" type="button">Distribution</button>
        </div>
      </div>
    </div>
  </section>

  <section class="wrap atlas-body">
    <div id="atlas-list">
{cards}
    </div>
    <p id="atlas-empty" class="empty-state" hidden>No entry matches that search. If you have hit a
      failure mode that is not here, <a href="https://github.com/syntropyrl/syntropyrl/issues/new">open an issue</a> -
      that is how this page grows.</p>
  </section>

  <section class="wrap narrow contribute">
    <h2>Missing an entry?</h2>
    <p>This page is the point of the project. If you have debugged an RL run at 2am, you know
      something that is not written down anywhere. A complete contribution is four things: an Atlas
      entry, a repro scenario, a detector, and a test that proves it fires on the repro and stays
      silent on a healthy run.</p>
    <a class="btn-primary" href="https://github.com/syntropyrl/syntropyrl/blob/main/CONTRIBUTING.md">How to contribute</a>
  </section>
</main>

<footer class="site-footer">
  <div class="wrap footer-inner">
    <span>syntropyrl - MIT licensed, zero dependencies.</span>
    <span class="footer-links">
      <a href="./index.html">Overview</a>
      <a href="./playground.html">Playground</a>
      <a href="https://github.com/syntropyrl/syntropyrl">GitHub</a>
    </span>
  </div>
</footer>

<script>
(function () {{
  var search = document.getElementById('atlas-search');
  var chips = Array.prototype.slice.call(document.querySelectorAll('.chip[data-filter]'));
  var entries = Array.prototype.slice.call(document.querySelectorAll('.entry'));
  var heads = Array.prototype.slice.call(document.querySelectorAll('.family-head'));
  var empty = document.getElementById('atlas-empty');
  var family = 'all';

  function apply() {{
    var q = (search.value || '').trim().toLowerCase();
    var shown = 0;
    entries.forEach(function (el) {{
      var okFamily = family === 'all' || el.getAttribute('data-family') === family;
      var okQuery = !q || (el.getAttribute('data-search') || '').indexOf(q) !== -1;
      var visible = okFamily && okQuery;
      el.hidden = !visible;
      if (visible) {{ shown++; }}
    }});
    heads.forEach(function (head) {{
      var fam = head.getAttribute('data-family');
      var any = entries.some(function (el) {{
        return !el.hidden && el.getAttribute('data-family') === fam;
      }});
      head.hidden = !any;
    }});
    empty.hidden = shown !== 0;
  }}

  search.addEventListener('input', apply);
  chips.forEach(function (chip) {{
    chip.addEventListener('click', function () {{
      chips.forEach(function (c) {{ c.classList.remove('is-active'); }});
      chip.classList.add('is-active');
      family = chip.getAttribute('data-filter');
      apply();
    }});
  }});
  apply();
}})();
</script>
</body>
</html>
""".format(n=len(rows), banner=BANNER, cards="\n".join(cards))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if files are stale")
    args = ap.parse_args()

    rows, orphan = _joined()
    targets = {
        os.path.join(ROOT, "ATLAS.md"): build_markdown(rows, orphan),
        os.path.join(ROOT, "docs", "atlas.html"): build_html(rows, orphan),
    }

    stale = []
    for path, content in targets.items():
        existing = None
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as fh:
                existing = fh.read()
        if existing == content:
            print("unchanged  {}".format(os.path.relpath(path, ROOT)))
            continue
        if args.check:
            stale.append(os.path.relpath(path, ROOT))
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print("wrote      {}".format(os.path.relpath(path, ROOT)))

    if stale:
        print(
            "\nThese generated files are stale: {}\n"
            "Run: python scripts/build_atlas.py".format(", ".join(stale))
        )
        return 1
    print("\n{} entries, {} without a detector".format(len(rows), len(orphan)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
